<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Product>LethalModUtils</Product>
    <Title>$(Product)</Title>
    <Authors>baer1</Authors>
    <Version>0.0.8</Version>
    <AssemblyName>$(Authors).$(Product)</AssemblyName>
    <Description>A collection of useful modding utilities for Lethal Company</Description>
    <PackageTags>lethal company;bepinex</PackageTags>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    <Copyright>Copyright (c) baer1 2025</Copyright>
    <PackageProjectUrl>https://github.com/baerchen201/LethalModUtils</PackageProjectUrl>
    <RepositoryUrl>https://github.com/baerchen201/LethalModUtils.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
    <None Include="icon.png" Pack="true" PackagePath="" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>$(Product)</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <RestoreAdditionalProjectSources>
            https://api.nuget.org/v3/index.json;
            https://nuget.bepinex.dev/v3/index.json
        </RestoreAdditionalProjectSources>
  </PropertyGroup>
  <PropertyGroup>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
    <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=./</PathMap>
    <!-- Exclude Test mod -->
    <DefaultItemExcludes>$(DefaultItemExcludes);ModUtilsTest/**</DefaultItemExcludes>
  </PropertyGroup>
  <!-- Primary Package References -->
  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference
      Include="BepInEx.AssemblyPublicizer.MSBuild"
      Version="0.4.3"
      PrivateAssets="all"
    />
    <PackageReference Include="BepInEx.Core" Version="5.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" PrivateAssets="all" />
    <PackageReference
      Include="LethalCompany.GameLibs.Steam"
      Version="*-*"
      Publicize="true"
      PrivateAssets="all"
    />
    <PackageReference
      Include="UnityEngine.Modules"
      Version="2022.3.62"
      IncludeAssets="compile"
      PrivateAssets="all"
    />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference
      Include="Microsoft.NETFramework.ReferenceAssemblies"
      Version="1.0.2"
      PrivateAssets="all"
    />
  </ItemGroup>
</Project>
